#Config file for dummy agent.
#----------------------------
#tick = seconds

#The collector IP and port.
communication: { 
  ws: 'ws://127.0.0.1:8888/' 
}

#All stuf you want to monitore.
psutil_cpu_count: { 
  tick: 5, 
  min_logical_cpu: 10, 
  min_cpu: 2 
}

psutil_process: { 
  tick: 0 
}
